name: run deno script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 4' # Every thursday at 7:00 am UTC

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed to clone the repository and create new releases

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        # Latest stable for a major
        with:
          deno-version: v2.x

      - name: Run tests
        run: deno test --allow-net=kinotickets.express

      - name: Build excecutable
        run: 'deno compile --allow-read --allow-write --allow-net main.ts --output cinemacorn'

      - name: execute deno
        run: ./cinemacorn

      - name: Get current date in yyyy-MM-dd format
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.date }}
          body_path: schedule.md
